### PR TITLE
fix test that fails periodically

### LINKED ISSUE #978: Fix test that fails periodically
The following test seems to fail periodically and randomly.  Investigate why.

`./spec/features/create_new_work_spec.rb:174:in block (4 levels) in <top (required)>`

```
Failure/Error: 
  expect(page).to have_content 'Keller, M. (2020, February). My Title. ' \
    "Stanford Digital Repository. Available at #{Work::LINK_TEXT}"

  expected to find text "Keller, M. (2020, February). My Title. Stanford Digital Repository. Available at :link will be inserted here automatically when available:" in "XXXXXXX.". (However, it was found 1 time including non-visible text.)
./spec/features/create_new_work_spec.rb:174:in `block (4 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made?

Fixes #978 - an attempt to fix the flappy test

## How was this change tested?

Test suite unflapped?

### CODE REVIEW

**Review by mjgiarlo — COMMENTED** [review]
I'll give it a run-through.

File: spec/features/create_new_work_spec.rb [hunk 1]
```diff
@@ -154,6 +154,8 @@
           click_button('Choose files')
         end
 
+        sleep 1 # pause to wait for file to upload
```
Comment (mjgiarlo) [inline spec/features/create_new_work_spec.rb:157]: I wanted to test this locally but I can't get the dang tests to fail: instead of sleeping for a fixed, hard-coded value, I wonder if we can get Capybara to do this for us via:

```suggestion
        expect(page).to have_content('sul.svg')
```

Happy to pair too since apparently you *can* see this fail locally.

File: spec/features/create_new_work_spec.rb [hunk 2]
```diff
@@ -171,6 +173,7 @@
         check 'I agree to the SDR Terms of Deposit'
         click_button 'Deposit'
 
+        expect(page).to have_current_path(work_path(Work.last)) # this will fail if validation fails
```
Comment (mjgiarlo) [inline spec/features/create_new_work_spec.rb:176]: :+1:

File: spec/features/create_new_work_spec.rb (hunk 1 above)
Comment (mjgiarlo) [reply spec/features/create_new_work_spec.rb]: This didn't do the trick.

**Comment by mjgiarlo** [comment]
@sul-dlss/infrastructure-team @peetucket and I sunk time into this and didn't come up with anything better than `sleep 1` and, given all the other work we want to do, felt the `sleep` was good enough for now. If anyone else is inclined to toss ideas at @peetucket or wants to take this on, I think that'd be welcome. Otherwise, I might recommend we move forward with this and iterate.

**Review by jcoyne — APPROVED** [review]
