### PR TITLE
DropZone checks for duplicate filenames

### LINKED ISSUE #1327: Provide feedback to user when they attempt to upload two files with the same name.
## Backtrace

    line 41 of [PROJECT_ROOT]/app/jobs/deposit_job.rb: create_or_update
    line 29 of [PROJECT_ROOT]/app/jobs/deposit_job.rb: deposit
    line 10 of [PROJECT_ROOT]/app/jobs/deposit_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/78735927)

### PR DESCRIPTION
**Pull request by jermnelson**
## Why was this change made?
Fixes #1327

## How was this change tested?
Tested in a feature test.

## Which documentation and/or configurations were updated?
n/a

### CODE REVIEW

File: app/packs/controllers/dropzone_controller.js [hunk 1]
```diff
@@ -35,6 +35,16 @@ export default class extends Controller {
     }
   }
 
+  checkForDuplicates(fileName) {
+    // Current files in dropZone
+    const fileNames = this.dropZone.files.map(file => { return file.name })
+    // Remove current fileName
+    fileNames.pop(fileName)
```
Comment (jcoyne) [inline app/packs/controllers/dropzone_controller.js:42]: Does pop take arguments?  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop

File: app/packs/controllers/dropzone_controller.js [hunk 2]
```diff
@@ -35,6 +35,16 @@ export default class extends Controller {
...
+    // Existing files for this Work
+    this.previewTargets.map(elem => { fileNames.push(elem.children[1].innerText.trim()) })
```
Comment (jcoyne) [inline app/packs/controllers/dropzone_controller.js:44]: It looks like you are doing a map, but aren't doing anything with the result. Would `forEach` be a better choice?

Comment (jcoyne) [reply app/packs/controllers/dropzone_controller.js:44]: Do we need line 40?  Don't each of them get added to the previewTargets?

Comment (jcoyne) [reply app/packs/controllers/dropzone_controller.js:44]: Instead of walking the DOM tree here, can you add a stimulus target attributes (`data-dropzone-target="fileName"`) to the fields and use `this.fileNameTargets`?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/packs/controllers/dropzone_controller.js [hunk 3]
```diff
@@ -75,10 +87,14 @@ export default class extends Controller {
 
   bindEvents() {
     this.dropZone.on("addedfile", file => {
+      if (this.checkForDuplicates(file.name) === true) {
```
Comment (jcoyne) [inline app/packs/controllers/dropzone_controller.js:90]: Do we need to compare here? Isn't this method returning a boolean?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/packs/controllers/dropzone_controller.js (hunk 1 above)
Comment (jermnelson) [reply app/packs/controllers/dropzone_controller.js]: Fixed in latest commit; using `Array.splice`

File: app/packs/controllers/dropzone_controller.js (hunk 2 above)
Comment (jermnelson) [reply app/packs/controllers/dropzone_controller.js]: Using new stimulus target attributes, removed dropZone in latest commit.

File: app/packs/controllers/dropzone_controller.js (hunk 3 above)
Comment (jermnelson) [reply app/packs/controllers/dropzone_controller.js]: Updated in latest commit.

**Review by jcoyne — APPROVED** [review]
