### PR TITLE
Raise custom exception when deposit status not available

### LINKED ISSUE #233: Raise custom exception when retrying deposit
In `DepositStatusJob`, raise a custom exception (`TryAgainLater`) when there is no result yet:

https://github.com/sul-dlss/happy-heron/blob/21359943aa15f095b6aba77ba48e19031db484f8/app/jobs/deposit_status_job.rb#L12

This exception is raised to force sidekiq to retry with exponential backoff. It is not meant to be logged to Honeybadger. As part of this work, add a new HB exception ignore for `TryAgainLater` (to shared_configs for all envs).

## Backtrace

    line 12 of [PROJECT_ROOT]/app/jobs/deposit_status_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/69184146)

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #233

## Why was this change made?

This exception is used to trigger Sidekiq retries and is not useful for reporting to Honeybadger. By using a custom exception class, we can ignore it in HB config. 

## How was this change tested?

CI

## Which documentation and/or configurations were updated?

Corresponding shared_configs work has already been done.

### CODE REVIEW

File: app/exceptions/try_again_later.rb [hunk 1]
```diff
@@ -0,0 +1,4 @@
+# typed: true
+# frozen_string_literal: true
+
+class TryAgainLater < RuntimeError; end
```
Comment (jcoyne) [inline app/exceptions/try_again_later.rb:4]: Can you add documentation here?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: app/exceptions/try_again_later.rb (hunk 1 above)
Comment (mjgiarlo) [reply app/exceptions/try_again_later.rb:4]: @jcoyne yep!

Comment (mjgiarlo) [reply app/exceptions/try_again_later.rb:9]: done

**Review by ndushay — APPROVED** [review]

**Review by jcoyne — APPROVED** [review]
