### PR TITLE
Prevent depositing into an unaccessioned collection

### LINKED ISSUE #604: Collection State cannot transition via "begin deposit"
Reported in #605 

[Happy Heron/qa] StateMachines::InvalidTransition: Cannot transition state via :begin_deposit from :depositing (Reason(s): State cannot transition via "begin deposit")

## Backtrace

    line 56 of [PROJECT_ROOT]/app/controllers/collections_controller.rb: after_save
    line 45 of [PROJECT_ROOT]/app/controllers/collections_controller.rb: update

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/70711245)

### LINKED ISSUE #605: Unable to deposit new version of collection
As reported by Amy when producing demo video:

1. Create a collection and deposit it.
2. Open a new version of a collection.
3. Edit the metadata and click  “deposit” again, it ran the validations but didn’t deposit anything.

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?
Fixes #605
FIxes #604

### CODE REVIEW

File: app/policies/work_policy.rb [hunk 1]
```diff
@@ -9,14 +9,17 @@ class WorkPolicy < ApplicationPolicy
...
   end
 
-  # Only administrators or depositors in a specific collection are able to create new collection members
+  # Can deposit a work iff:
+  #   1. Collection is accessioned
+  #   2. The user is an administrator, or a depositor or a manager of this collection
   sig { returns(T::Boolean) }
   def create?
+    collection = record.collection
+    return false unless collection.accessioned?
```
Comment (mjgiarlo) [inline app/policies/work_policy.rb:18]: Do we need a new work policy spec to cover this or does the current set of specs already cover this?

File: app/policies/collection_policy.rb [hunk 2]
```diff
@@ -27,10 +25,10 @@ def update?
     administrator? || manages_collection?(record)
   end
 
-  # Can works be deposited into this collection
+  # Can this collection be deposited
   sig { returns(T::Boolean) }
   def deposit?
-    NO_DEPOSIT_STATUS.exclude? record.state
+    record.can_begin_deposit?
```
Comment (mjgiarlo) [inline app/policies/collection_policy.rb:31]: A magic method, I assume. Where's it from? What's it doing?

**Review by mjgiarlo — APPROVED** [review]
I have a couple minor questions. Approving in meantime.

File: app/policies/collection_policy.rb (hunk 2 above)
Comment (jcoyne) [reply app/policies/collection_policy.rb:31]: It's from the state-machine gem. It checks to see if it's in a state where it could do the begin_deposit transition.

File: app/policies/work_policy.rb (hunk 1 above)
Comment (jcoyne) [reply app/policies/work_policy.rb:18]: I believe it's already covered in the work_policy_spec.rb
