### PR TITLE
Fix description message for new item without values.

### LINKED ISSUE #2632: Fix description message for new item without values
When a brand new item is saved without doing anything at all to the form, there shouldn't be anything displayed in the description. Right now this says "citation modified, visibility modified, license modified". Or at least it did for a new item in the collection I was using for testing. This may vary depending on the collection settings.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #2632

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in addition to specs. ⚡

Unit

### CODE REVIEW

File: spec/services/work_version_event_description_builder_spec.rb [hunk 1]
```diff
@@ -179,4 +179,95 @@
...
   end
+
+  context 'when a new work version and nothing has changed' do
+    let(:user) { build(:user) }
+    let(:collection) { build(:collection, required_license: 'CC0-1.0', release_option: 'immediate', access: 'world') }
+    let(:work) { Work.new(collection: collection, depositor: user, owner: user) }
+    let(:work_version) { WorkVersion.new(work: work) }
+
+    context 'when nothing has changed' do
+      # let(:params) do
```
Comment (jcoyne) [inline spec/services/work_version_event_description_builder_spec.rb:190]: Can this be removed?

**Review by jcoyne — CHANGES_REQUESTED** [review]

File: spec/services/work_version_event_description_builder_spec.rb (hunk 1 above)
Comment (justinlittman) [reply spec/services/work_version_event_description_builder_spec.rb]: Yes. Fixed.

**Review by jcoyne — APPROVED** [review]
